// Generated by Selenium IDE

import org.junit.jupiter.api.*;
import org.openqa.selenium.By;

public class GroupCreationTests extends TestBase {


    @Test
    public void canCreateGroup() {
        openGroupsPage();
        createGroup("group_name_1", "group_header_1", "group_footer_1");
    }


    @Test
    public void canCreateGroupWithEmptyName() {
        openGroupsPage();
        createGroup("", "", "");
    }
}
