// Generated by Selenium IDE
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class GroupRemovalTests extends TestBase {

    @Test
    public void CanRemoveGroup() {
        openGroupsPage();
        if (!isGroupPresent()) {
            createGroup("group_name", "group_header", "group_footer");
        }
        removeGruop();
    }

}
